### ISSUE TITLE
the checkpoint files in README seems mismatch the tensorflow version in requirement

### ISSUE THREAD

**Issue by ShuyeHan** [cvalenzuela/scenescoop#1]
I tried to test the im2txt model but was stuck in executing the below command in the tutorial:

`bazel-bin/im2txt/run_inference \
  				   --checkpoint_path=${CHECKPOINT_DIR} \
                                   --vocab_file=${VOCAB_FILE} \
                                   --input_files=${IMAGE_FILE}`

with the error showing that:

`tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "lstm/basic_lstm_cell/weights" not found in checkpoint files /home/ubuntu/im2txt/model.ckpt-3000000`

This seems to be a mismatch problem between the checkpoint files and the tensorflow version. But I installed exactly the version in requirement.txt ( which is 1.1.0). And I downloaded exactly the same pretrained model in the link in README file.

**Comment by cvalenzuela** [comment]
Which instructions are you following? 
Have you tried this: https://edouardfouche.com/Fun-with-Tensorflow-im2txt/ ?

**Comment by ShuyeHan** [comment]
That model did work, with an older tf version 0.12.1. So are we suggested to use the older version and model in the link instead of the 1.1.0 version in requirements.txt and models in README?

**Comment by cvalenzuela** [comment]
The models should be the same, but I'll double check.
If that worked for you, then probably there's a mismatch in the requirements.txt. Feel free to make PR if you fixed it.
